[package]
name = "merkle-domdiff"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4.3"
regex = "1.11.1"
sha2 = "0.10.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
